---
extends:
    - react-app
    - react-app/jest
rules:
    no-console: warn
    prefer-const: warn
    indent: 
        - warn
        - 4
    max-len:
        - warn
        - code: 200
    jsx-quotes:
        - warn 
        - prefer-double
    quotes: 
        - warn 
        - single
    comma-dangle:
        - warn
        - never
...